version: "3.9"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
